using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

// Genere dynamiquement le menu "Scene" (une entree par scene trouvee sous Assets/Project/Scenes)
// en ecrivant SceneMenuItems.Generated.cs. Se regenere automatiquement quand une scene
// est ajoutee/supprimee/deplacee dans ce dossier, ou via Scene > Refresh Scene List.
internal static class SceneMenuGenerator
{
    private const string ScenesRootFolder = "Assets/Project/Scenes";
    private const string GeneratedFilePath = "Assets/Project/Scripts/Editor/SceneMenuItems.Generated.cs";

    [InitializeOnLoadMethod]
    private static void EnsureGeneratedOnLoad()
    {
        if (!File.Exists(GeneratedFilePath))
        {
            Generate();
        }
    }

    [MenuItem("Scene/Refresh Scene List", priority = 1000)]
    private static void RefreshMenuItem()
    {
        Generate();
    }

    private class ScenePostprocessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            bool relevant = importedAssets.Concat(deletedAssets).Concat(movedAssets).Concat(movedFromAssetPaths)
                .Any(path => path.Replace('\\', '/').StartsWith(ScenesRootFolder) && path.EndsWith(".unity"));

            if (relevant)
            {
                Generate();
            }
        }
    }

    private static void Generate()
    {
        var scenePaths = Directory.GetFiles(ScenesRootFolder, "*.unity", SearchOption.AllDirectories)
            .Select(p => p.Replace('\\', '/'))
            .OrderBy(p => p, System.StringComparer.OrdinalIgnoreCase)
            .ToList();

        var usedMethodNames = new System.Collections.Generic.HashSet<string>();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Genere automatiquement par SceneMenuGenerator. Ne pas editer a la main.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using UnityEditor;");
        sb.AppendLine("using UnityEditor.SceneManagement;");
        sb.AppendLine();
        sb.AppendLine("internal static class SceneMenuItems");
        sb.AppendLine("{");

        int priority = 1;
        foreach (var scenePath in scenePaths)
        {
            string relative = scenePath.Substring(ScenesRootFolder.Length + 1);
            string withoutExt = relative.Substring(0, relative.Length - ".unity".Length);
            string menuPath = "Scene/" + withoutExt;

            string methodName = "Open_" + SanitizeIdentifier(withoutExt);
            while (!usedMethodNames.Add(methodName))
            {
                methodName += "_";
            }

            sb.AppendLine($"    [MenuItem(\"{EscapeForCSharpString(menuPath)}\", priority = {priority})]");
            sb.AppendLine($"    private static void {methodName}()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;");
            sb.AppendLine($"        EditorSceneManager.OpenScene(\"{EscapeForCSharpString(scenePath)}\");");
            sb.AppendLine("    }");
            sb.AppendLine();

            priority++;
        }

        sb.AppendLine("}");

        File.WriteAllText(GeneratedFilePath, sb.ToString(), Encoding.UTF8);
        AssetDatabase.ImportAsset(GeneratedFilePath);
    }

    private static string SanitizeIdentifier(string s)
    {
        var chars = s.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
        var result = new string(chars);
        if (result.Length == 0 || char.IsDigit(result[0]))
        {
            result = "_" + result;
        }
        return result;
    }

    private static string EscapeForCSharpString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
